// 주석기능도 추가

server {
	listen 8080;
	server_name	localhost;
	root /home/wpark/Documents/webserv/test/nginx/
	error_page /error.html 
	client_max_body_size 1M; // default

	autoindex on;
	location / {
		allow GET;
		autoindex off;
		root /home/wpark/Documents/webserv/
	}
	location /test {

	}
}

server