server {
	listen 8080;
	# server_name	localhost;
	root ./www/;
	# error_page ./www/error.html;

	client_max_body_size 200M; # 123 123M 123m 123K 123k

	location / {
		allow GET;
		index youpi.bad_extension default.html;
		autoindex on;
		root ./www/;
		# cgi .php /usr/bin/php-cgi;
	}
	location /directory/ {
		# allow POST HEAD OPTIONS DELETE;
		autoindex on;
		index youpi.bad_extension;
		cgi .bla ./www/ubuntu_cgi_tester;
		root ./www/YoupiBanane;
	}

	location /put_test/ {
		index youpi.bad_extension;
		# cgi .php /usr/bin/php-cgi;
		root ./www/YoupiBanane;
		upload_folder ./www/upload/;
	}

	location /post_body {
		client_max_body_size 100;
		index youpi.bad_extension;
		# cgi .php /usr/bin/php-cgi;
		root ./www/;
		# upload_folder ./www/upload/;
	}
}
