server {
	listen 8080;
	server_name	localhost;
	# root /home/wpark/Documents/webserv/www/;
	root /home/user42/Desktop/projects/webserv/;
	# root /home/user42/Desktop/mashar/projects/webserv/;
	error_page /home/user42/Desktop/projects/webserv/www/error.html;
	# error_page /home/user42/Desktop/mashar/projects/webserv/www/error.html;
	# client_max_body_size 1M;
	# error_page /home/wpark/Documents/webserv/www/YoupiBanane/youpi.bad_extension;

	# autoindex on;
	location / {
		# allow POST HEAD OPTIONS DELETE;
		# autoindex on;
		allow GET;
		index youpi.bad_extension;
		cgi .php /usr/bin/php-cgi;

		# allow POST HEAD OPTIONS DELETE;
		autoindex on;
		# root /home/wpark/Documents/webserv/www/;
		root /home/user42/Desktop/projects/webserv/;
		# root /home/user42/Desktop/mashar/projects/webserv;
	}

	location /directory/ {
		# allow POST HEAD OPTIONS DELETE;
		# autoindex on;
		index youpi.bad_extension;
		# cgi .php /usr/bin/php-cgi;

		# allow POST HEAD OPTIONS DELETE;
		autoindex on;
		# root /home/wpark/Documents/webserv/www/;
		root /home/user42/Desktop/projects/webserv/YoupiBanane; 
		# root /home/user42/Desktop/mashar/projects/webserv;
	}
	# location /test/ {
	# 	allow GET POST;
	# 	autoindex on;
		
	# 	root /home/wpark/Documents/webserv/www/;
	# 	# which php-cgi
	# 	cgi .php /usr/bin/php-cgi;
	# }
}
