# /etc/hosts
# 127.0.0.1 mydomain.com

# curl http://mydomain.com:8000/default.html
server {
	error_page ./www/error.html;
	server_name mydomain.com;
	listen 8000;
	root ./www/;
}

# curl http://localhost:8080/default.html
server {
	client_max_body_size 20;
	server_name localhost;
	root ./www/YoupiBanane/;
	listen 8080;
}