server {
	listen 8000;
	root /home/user42/Desktop/mashar/projects/webserv/www/;
	server_name localhost;
	location / {
		index youpi.bad_extension default.html;
		autoindex on;
		root /home/user42/Desktop/mashar/projects/webserv/www/;

	}

	location /directory/ {
		autoindex on;
		index youpi.bad_extension;
		# cgi .bla ./www/ubuntu_cgi_tester;
		root /home/user42/Desktop/mashar/projects/webserv/www/YoupiBanane/;
	}

	location /put_test/ {
		index youpi.bad_extension;
		root /home/user42/Desktop/mashar/projects/webserv/www/YoupiBanane/;
		# upload_folder ./www/upload/;
	}

	location /post_body {
		client_max_body_size 100;
		index youpi.bad_extension;
		root /home/user42/Desktop/mashar/projects/webserv/www/;
	}

	location /upload {
		root /home/user42/Desktop/mashar/projects/webserv/www/;
		# client_body_temp_path /home/wpark/Documents/webserv/www;
		dav_methods PUT DELETE;
		# create_full_put_path   on;
		# dav_access group:rw all:r;	}
	}
}