server {
	listen 8000;
	root /home/wpark/Documents/webserv/www/;
	server_name localhost;

	location /upload {
		root /home/wpark/Documents/webserv/www/;
		# client_body_temp_path /home/wpark/Documents/webserv/www;
		dav_methods PUT DELETE;
		create_full_put_path   on;
		dav_access group:rw all:r;
  		# create_full_put_path  on;
	    # dav_access group:rw all:r;

	}
}