server {
	listen 8000;
	root /home/wpark/Documents/webserv/www/;

	location / {
		# dav_methods  PUT;
		# create_full_put_path  on;
	    # dav_access group:rw all:r;
		autoindex on;
		index abcd.html;
	}
}